# docker-compose.yml (in your project root)
version: '3.8'

services:
  frontend:
    build:
      context: . # Refers to the Dockerfile at the root
      dockerfile: Dockerfile
    ports:
      - "3000:8080" # Maps host port 3000 to container port 8080
    environment:
      # How your frontend React app in the browser will call the backend API
      # 'backend' refers to the service name in Docker Compose's internal DNS
      - VITE_REACT_APP_API_URL=http://backend:8080 # Update this for Vite if you're using it
    depends_on:
      - backend

  backend:
    build:
      context: ./server # Refers to the Dockerfile in the server/ directory
      dockerfile: Dockerfile
    environment:
      - PORT=8080 # Ensure backend Express app listens on this for internal Docker Compose
    # If you want to access the backend directly from your host for testing (e.g., Postman)
    # you can add:
    # ports:
    #   - "8081:8080" # Maps host port 8081 to container port 8080